import assert from "node:assert/strict";
import test from "node:test";
import { buildLiveSearchRequest } from "../app/live-search.ts";
import { buildRentCastUrl, normalizeRentCastListing, searchRentCast } from "../app/providers.ts";

const sample = { id:"la-1", addressLine1:"101 Industrial Street", formattedAddress:"101 Industrial Street, Los Angeles, CA 90013", city:"Los Angeles", neighborhood:"Arts District", state:"CA", zipCode:"90013", latitude:34.0407, longitude:-118.2351, price:2700, bedrooms:1, bathrooms:1, squareFootage:850, status:"Active", lastSeenDate:"2026-08-24T12:00:00.000Z", listingUrl:"https://example.com/listing", description:"Industrial loft with parking, in-unit washer and exposed brick", imageUrl:"https://images.example.com/la-1.jpg" };

test("normalizes a RentCast record into the Receiver contract", () => { const listing=normalizeRentCastListing(sample,new Date("2026-08-25T12:00:00.000Z")); assert.ok(listing); assert.equal(listing.id,"rentcast:la-1"); assert.equal(listing.rent,2700); assert.equal(listing.sourceUrl,"https://example.com/listing"); assert.deepEqual(listing.warehouseSignals,["Loft","Industrial conversion"]); assert.deepEqual(listing.features,["Parking","Laundry"]); assert.equal(listing.freshness,"live"); });
test("normalizes pet-friendly and furnished provider language into canonical UX features", () => { const listing=normalizeRentCastListing({...sample,id:"la-pet",description:"Fully furnished loft. Cats allowed and dogs allowed. Assigned garage space."}); assert.ok(listing); assert.ok(listing.features.includes("Pet friendly")); assert.ok(listing.features.includes("Furnished")); assert.ok(listing.features.includes("Parking")); });
test("rejects provider records without authentic listing imagery",()=>assert.equal(normalizeRentCastListing({...sample,imageUrl:undefined,photos:undefined}),null));
test("rejects provider records that do not preserve an exact listing source",()=>assert.equal(normalizeRentCastListing({...sample,listingUrl:undefined,url:undefined}),null));
test("enforces hard amenity and warehouse requirements on live results",async()=>{const request=buildLiveSearchRequest("industrial loft with parking under $3,000"); const fetcher=async()=>new Response(JSON.stringify([sample,{...sample,id:"la-2",addressLine1:"202 Conventional Street",description:"Conventional apartment with laundry"},{...sample,id:"la-3",addressLine1:"303 Loft Street",description:"Industrial loft without assigned amenities"}]),{status:200}); const results=await searchRentCast(request,{rentCastApiKey:"test"},fetcher,new Date("2026-08-25T12:00:00.000Z")); assert.deepEqual(results.map(x=>x.id),["rentcast:la-1"]);});
test("builds a bounded LA RentCast query from search intent",()=>{const url=buildRentCastUrl(buildLiveSearchRequest("one bedroom in West Hollywood under $2,800")); assert.equal(url.searchParams.get("city"),"West Hollywood"); assert.equal(url.searchParams.get("price"),"0:2800"); assert.equal(url.searchParams.get("bedrooms"),"1:"); assert.equal(url.searchParams.get("status"),"Active"); assert.equal(url.searchParams.get("limit"),"50");});
test("treats broad south/east language as ranking preference rather than excluding otherwise valid LA candidates",async()=>{const request=buildLiveSearchRequest("warehouse-style apartments south or east of LA"); const fetcher=async()=>new Response(JSON.stringify([sample,{...sample,id:"la-east",addressLine1:"202 East Loft",latitude:34.03,longitude:-118.1}]),{status:200}); const results=await searchRentCast(request,{rentCastApiKey:"test"},fetcher); assert.equal(results.length,2); assert.equal(results[0].id,"rentcast:la-east");});
test("uses conservative neighborhood estimates for Santa Monica commute without a Routes key",async()=>{const request=buildLiveSearchRequest("loft within 50 minutes of Santa Monica"); const fetcher=async()=>new Response(JSON.stringify([sample,{...sample,id:"weho",addressLine1:"202 WeHo Loft",city:"West Hollywood",neighborhood:"West Hollywood"},{...sample,id:"pasadena",addressLine1:"303 Pasadena Loft",city:"Pasadena",neighborhood:"Pasadena"}]),{status:200}); const results=await searchRentCast(request,{rentCastApiKey:"test"},fetcher,new Date("2026-08-25T12:00:00.000Z")); assert.deepEqual(results.map(x=>x.id).sort(),["rentcast:la-1","rentcast:weho"].sort()); const arts=results.find(x=>x.id==="rentcast:la-1"); assert.equal(arts?.commute?.estimated,true); assert.deepEqual(arts?.commute?.range,[45,50]); assert.equal(arts?.commute?.minutes,50);});
test("estimated commute uses the upper bound when enforcing a ceiling",async()=>{const request=buildLiveSearchRequest("loft within 45 minutes of Santa Monica"); const fetcher=async()=>new Response(JSON.stringify([{...sample,id:"silver",addressLine1:"Silver Lake Loft",city:"Los Angeles",neighborhood:"Silver Lake"},{...sample,id:"arts",addressLine1:"Arts Loft",neighborhood:"Arts District"}]),{status:200}); const results=await searchRentCast(request,{rentCastApiKey:"test"},fetcher); assert.deepEqual(results.map(x=>x.id),["rentcast:silver"]);});
test("adds traffic-aware commute minutes and removes over-limit routes when Routes is configured",async()=>{const request=buildLiveSearchRequest("industrial lofts within 45 minutes of Santa Monica"); let call=0; const fetcher=async()=>{call++; if(call===1)return new Response(JSON.stringify([sample,{...sample,id:"la-2",addressLine1:"202 Far Street",latitude:34.2,longitude:-117.9}]),{status:200}); return new Response(JSON.stringify([{originIndex:0,destinationIndex:0,condition:"ROUTE_EXISTS",status:{},duration:"2400s"},{originIndex:1,destinationIndex:0,condition:"ROUTE_EXISTS",status:{},duration:"3600s"}]),{status:200});}; const results=await searchRentCast(request,{rentCastApiKey:"test",googleRoutesApiKey:"google"},fetcher,new Date("2026-08-25T12:00:00.000Z")); assert.equal(results.length,1); assert.equal(results[0].commute?.minutes,40); assert.equal(results[0].commute?.estimated,false);});
test("fails explicitly when Google Routes is temporarily unavailable",async()=>{const request=buildLiveSearchRequest("loft within 45 minutes of Santa Monica"); let call=0; const fetcher=async()=>++call===1?new Response(JSON.stringify([sample]),{status:200}):new Response("unavailable",{status:503}); await assert.rejects(searchRentCast(request,{rentCastApiKey:"test",googleRoutesApiKey:"google"},fetcher),/Google Routes returned 503/);});
